import numpy as np


def get_color(index=None):
    # cnames = list(matplotlib.colors.cnames.keys())
    # cnames.sort()
    cnames = [
        # 'aliceblue',
        'antiquewhite',
        'aqua',
        'aquamarine',
        ##'azure',
        'beige',
        'bisque',
        'black',
        'blanchedalmond',
        'blue',
        'blueviolet',
        'brown',
        'burlywood',
        'cadetblue',
        'chartreuse',
        'chocolate',
        'coral',
        'cornflowerblue',
        # 'cornsilk',
        'crimson',
        'cyan',
        'darkblue',
        'darkcyan',
        'darkgoldenrod',
        # 'darkgray',  # 和 darkgrey 有点像
        'darkgreen',
        'darkgrey',
        'darkkhaki',
        'darkmagenta',
        'darkolivegreen',
        'darkorange',
        'darkorchid',
        'darkred',
        'darksalmon',
        'darkseagreen',
        'darkslateblue',
        'darkslategray',
        'darkslategrey',
        'darkturquoise',
        'darkviolet',
        'deeppink',
        'deepskyblue',
        'dimgray',
        'dimgrey',
        'dodgerblue',
        'firebrick',
        # 'floralwhite',
        'forestgreen',
        'fuchsia',
        'gainsboro',
        # 'ghostwhite',
        'gold',
        'goldenrod',
        'gray',
        'green',
        'greenyellow',
        'grey',
        # 'honeydew',
        'hotpink',
        'indianred',
        'indigo',
        # 'ivory',
        'khaki',
        'lavender',
        'lavenderblush',
        'lawngreen',
        'lemonchiffon',
        'lightblue',
        'lightcoral',
        'lightcyan',
        'lightgoldenrodyellow',
        'lightgray',
        'lightgreen',
        'lightgrey',
        'lightpink',
        'lightsalmon',
        'lightseagreen',
        'lightskyblue',
        'lightslategray',
        'lightslategrey',
        'lightsteelblue',
        # 'lightyellow',
        'lime',
        'limegreen',
        'linen',
        'magenta',
        'maroon',
        'mediumaquamarine',
        'mediumblue',
        'mediumorchid',
        'mediumpurple',
        'mediumseagreen',
        'mediumslateblue',
        'mediumspringgreen',
        'mediumturquoise',
        'mediumvioletred',
        # 'midnightblue',
        'mintcream',
        'mistyrose',
        'moccasin',
        'navajowhite',
        'navy',
        # 'oldlace',
        'olive',
        'olivedrab',
        'orange',
        'orangered',
        'orchid',
        'palegoldenrod',
        'palegreen',
        'paleturquoise',
        'palevioletred',
        'papayawhip',
        'peachpuff',
        'peru',
        'pink',
        'plum',
        'powderblue',
        'purple',
        'rebeccapurple',
        'red',
        'rosybrown',
        'royalblue',
        'saddlebrown',
        'salmon',
        'sandybrown',
        'seagreen',
        # 'seashell',
        'sienna',
        'silver',
        'skyblue',
        'slateblue',
        # 'slategray',  # 和slategrey有点像
        'slategrey',
        'snow',
        'springgreen',
        'steelblue',
        'tan',
        'teal',
        'thistle',
        'tomato',
        'turquoise',
        'violet',
        'wheat',
        # 'white',
        # 'whitesmoke',
        'yellow',
        'yellowgreen']

    cnames = ['aqua', 'darkorange', 'cornflowerblue', 'deeppink', 'navy']

    if (index is None) or (index >= len(cnames)):
        index = np.random.randint(0, len(cnames))

    return cnames[index]


def get_linestyle(index=None):
    # linestyle = matplotlib.style.available
    linestyle = [#'.',
                 #',',
                 #'o',
                 #'v',
                 #'^',
                 #'<',
                 #'>',
                 #'1',
                 #'2',
                 #'3',
                 #'4',
                 #'s',
                 #'p',
                 #'*',
                 #'h',
                 #'H',
                 #'+',
                 #'x',
                 #'D',
                 #'d',
                 #'|',
                 #'_'
                 ]
    linestyle = [
        '-',
        '--',
        '-.',
        ':',
        # 'None', draw nothing, 相当于画点
        # ' ', draw nothing, 相当于画点
        # '', draw nothing, 相当于画点
    ]

    if (index is None) or (index >= len(linestyle)):
        index = np.random.randint(0, len(linestyle))

    return linestyle[index]
